### ISSUE TITLE
QSPI image buffer

### ISSUE THREAD

**Issue by MyVanitar** [kotetsuy/TouchGFXDemo#1]
Hi. Thank you for your work.

I could not find where you have assigned the images to the QSPI flash memory and where you read them. I appreciate if you point out.

**Comment by kotetsuy** [comment]
QSPI memory address is fixed in STM32.
When you build this code, the linker assigns internal flash and external QSPI automatically.
If you would like write the binary to QSPI, you need to use STM32cubeprogrammer and my original STLDR.
See also
*.stldr for flash W25Q128JV.
https://github.com/kotetsuy/STLDR

**Comment by MyVanitar** [comment]
Oh, that sounds good because in all examples which I saw from the QSPI memory mapping in STM32, people were modifing many many things for this to be enabled. and using attributes in the code to assing things to the external memory.

If I understand cirrectly, the only thing I should do is to config the QSPI correctly and use the MCU as normal. Like it has 16M flash size in your case, however the loader might be different for different flash chips. Mine is W25Q32

**Comment by kotetsuy** [comment]
> If I understand cirrectly, the only thing I should do is to config the QSPI correctly and use the MCU as normal.
Yes. You are right. And, you need to modify my STLDR for the only size.

**Comment by MyVanitar** [comment]
Thank you.

So for the QSPI flash config, I will check your CubeMX project.

Do you have a suggestion for STM32 MCUs that only have SPI interface?

**Comment by kotetsuy** [comment]
Unfortunately, no way is STM32 which has only SPI. You need to choose STM32 with QSPI.

**Comment by MyVanitar** [comment]
I initialized the QSPi and added this code the same as you

`__IO uint8_t *qspi_addr = (__IO uint8_t *)(0x90000000);`

but I don't see the Flash size increase in the compiler. is there anything else I should do?

**Comment by MyVanitar** [comment]
I solved the problem. Thanks. It was not about your code
